### ISSUE TITLE
Validation of runtimes

### ISSUE THREAD

**Issue by TheSriram** [awslabs/aws-lambda-builders#30]
**Description:**

Runtime Validation for python works by invoking the python executable in the path to check if the local python runtime version matches the required runtime.

This relies on how the path is setup to find the appropriate version of python.

**ISSUE**

* When trying to build python2.7 lambda applications from within a sam installation housed in a python3.6 environment, one sees the following error message.

```bash
(venv) srirammv@localrainbow:~/sam-app$sam build
2018-11-26 13:40:16 Building resource 'HelloWorldFunction'
Build Failed
Error: python executable found in your path does not match runtime.
 Expected version: python2.7, Found version: python3.6.
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
```

**WORKAROUND:**

Fixing this involves following steps:

* Moving up python executable of version python2.7 on the path
```
export PATH=/usr/bin:$PATH
python --version
2.7.10
```

```
(venv) srirammv@localrainbow::~/sam-app$sam build
2018-11-26 13:58:56 Building resource 'HelloWorldFunction'
2018-11-26 13:58:56 Running PythonPipBuilder:ResolveDependencies
2018-11-26 13:58:57 Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Package: sam package --s3-bucket <yourbucket>
```

**PERMANENT FIX**

A more permanent fix is in the works: https://github.com/awslabs/aws-lambda-builders/pull/35

line in question: https://github.com/awslabs/aws-lambda-builders/blob/develop/aws_lambda_builders/validate.py#L17

**RELATED GITHUB ISSUE**
* https://github.com/awslabs/aws-sam-cli/issues/797

**Comment by visini** [comment]
@TheSriram I have the reverse issue –  what do you suggest? Thanks!

```
2018-12-03 17:29:16 Found credentials in environment variables.
2018-12-03 17:29:16 Building resource 'HelloWorldFunction'
Error: python executable found in your path does not match runtime. 
 Expected version: python3.6, Found version: python2.7. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
Build Failed
```

**Comment by AdamShechter9** [comment]
I also have the reverse issue

2018-12-03 21:28:06 Found credentials in environment variables.
2018-12-03 21:28:06 Building resource 'HelloWorldFunction'
Build Failed
Error: python executable found in your path does not match runtime. 
 Expected version: python3.6, Found version: python2.7. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30

**Comment by visini** [comment]
Hi Adam, I finally got this to work. I'm suspecting that like me, you're trying to run this on macOS. Make sure you’re running python 3.6. If you’ve installed python via brew like me, you may run into issues when deploying from PyCharm.

check in console:
```
python -V
# Python 2.7.1
```

If you’re output above is 3.6.*, you're fine. If not, you need to make sure the command `python` points to your python 3.6.* installation.

add the following line to the top of `/etc/paths` by running `sudo nano /etc/paths` and saving it:
/usr/local/opt/python/libexec/bin

Then, confirm your Python version again with:

```
python -V
# Python 3.6.5
```

You should be all set!

**Comment by TheSriram** [comment]
What @visini says is correct. You need to have python3.6 installed, and also make sure its the first python in your path. Doing the following will let tell you, where the current python is coming from, and its rank in the path. You need to move the path where python3.6 is installed above the path from were your current python is.
```
which python
echo $PATH
```

**Comment by AdamShechter9** [comment]
thank you guys for the instruction.
I did have to redo my $PATH and put /usr/local/bin at the top.
I also had to redo the symbolic links in that folder, so python points to ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3

**Comment by oxbits** [comment]
I had to force my link:
`ln -fs /usr/local/bin/python3 /usr/local/bin/python`

**Comment by marakere** [comment]
@visini - Thanks for the info. Unfortunately I have latest Python version, but still, sam complains about the version. 

bash-3.2$ python -V
Python 3.7.0

bash-3.2$ sam build
2018-12-18 17:31:35 Found credentials in shared credentials file: ~/.aws/credentials
2018-12-18 17:31:36 Building resource 'HelloWorldFunction'
**Build Failed**
Error: python executable found in your path does not match runtime. 
 Expected version: python3.6, Found version: python2.7. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30

Do you think below might be the problem? when I issue which python, it takes me to system provided python2.7

bash-3.2$ which python
/usr/bin/python

bash-3.2$ /usr/bin/python
Python 2.7.10 (default, Aug 17 2018, 19:45:58) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by rustyautopsy** [comment]
I have also run into this issue. I have been able to get a little further down the rabbit hole.

I am running a MAC and followed these commands from @visini post.

```bash
brew upgrade
brew update
brew tap aws/tap
brew install aws-sam-cli
```

*NOTE:* I was trying to use the `pip` installed version of `aws-sam-cli` and it didn't work.

I then created a new `AWS Serverless Application` in Pycharm, with a new Virtaulenv set to use `python3.6`.

When finished I tried to 'Deploy' the app via PyCharm and it failed with the `Expected version: python3.6, Found version: python2.7. ` error.

So I then...

- dropped down to the `cli` in Pycharm with the virtualenv active `sam build` WORKS when run manually.
- jumping out of PyCharm and issued the same commands in `iTerm`, and those failed with the same `Expected version: python3.6, Found version: python2.7. `. When running this command the virtaulenv WAS NOT active.
- `source venv/bin/activate` and then `sam build` and SUCCESS.

My question now is when PyCharm issues the same `sam build` command is it respecting the virtaulenv the project is setup in?

**Comment by rustyautopsy** [comment]
At this time I can develop locally without the need to create custom PyCharm Run Configs so that's a win.

The deployment issues will need to get worked out, however, in our deployment pipelines, we would be running the native `sam build/deploy` commands anyway.

I suppose allowing devs to deploy `alpha` stacks from PyCharm would be cool for some smoke tests and some form of integration testing. So let's hope the deploy items get sorted soonish.

Cheers.

**Comment by dolosplus** [comment]
I have the opposite problem. See below. Has anyone solve this problem yet?

Error: python executable found in your path does not match runtime. 
 **Expected version: python3.6, Found version: python3.7.** 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30

**Comment by imohd23** [comment]
FINALLY IT BUILD FOR ME!
I had the issue of runtime executable in python:

```
2019-02-06 22:31:54 Found credentials in shared credentials file: ~/.aws/credentials
2019-02-06 22:31:54 Building resource 'HelloWorldFunction'
Build Failed
Error: python executable found in your path does not match runtime. 
 Expected version: python3.6, Found version: python2.7. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
```

So, I did the following:
1- make an alias for python2.7 to python3.6:
`alias python2.7=python3.6`

2- move python 3.6 from its path to another executable path:
`mv /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /usr/local/bin/python`

3- update `~/.bash_profile`:
`PAHT=~/usr/local/bin:$PATH` above `PATH=~/.local/bin:$PATH`

4- `sam build` !

I got:

`
Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Package: sam package --s3-bucket <yourbucket>
`

I'm using `MacBook Mojave 10.14.2`

**Comment by ryanpeach** [comment]
That sounds like it will completely butcher my environment's though. Not worth it at all. Needs a real fix.

**Comment by TheSriram** [comment]
Do you have the latest `aws-sam-cli` and `aws-lambda-builders` installed, this should have been fixed now. As long as you have the python version installed and its somewhere on the PATH, building of your lambda function should succeed.

**Comment by TheSriram** [comment]
from 0.12.0 of aws-sam-cli, this should be resolved. Closing this issue.

**Comment by richard-pal** [comment]
It is still an issue with SAM CLI 1.15.0

As a workaround the unversioned symlinks for python can be used:
echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/python@3.8/libexec/bin:$PATH"' >> ~/.profile

**Comment by timotheecour4** [comment]
Could we re-open? this is still an issue:

```
sam build -t cdk.out/MyStack.template.json --debug

2022-05-31 18:36:27,987 | Invalid executable for python at /pathto/MyStack/.venv/bin/python
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.50.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 66, in wrapper
    valid_path = binary_checker.validator.validate(executable_path)
  File "/usr/local/Cellar/aws-sam-cli/1.50.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/validator.py", line 51, in validate
    raise MisMatchRuntimeError(language=self.language, required_runtime=self.runtime, runtime_path=runtime_path)
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime.
 Expected version: python3.8, Found version: /pathto/MyStack/.venv/bin/python.
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30

Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/pathto/MyStack/.venv/bin/python'] which did not satisfy constraints for runtime: python3.8. Do you have python for runtime: python3.8 on your PATH?
```

we should have better isolation (possibly like homebrew is doing via setting environment variables internally)

**Comment by Sidzeppelin95** [comment]
Even after changing the runtime environment to python3.7 which is the version in the cli it is still showing me the following runtime error. It has been deployed but not building.
Building codeuri: /home/cloudshell-user/samapp/hello_world_function runtime: python3.9 metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']

Build Failed
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/usr/bin/python', '/bin/python'] which did not satisfy constraints for runtime: python3.9. Do you have python for runtime: python3.9 on your PATH?
